#
# kdave/Chart.yaml
#
# Kdave Helm chart.
#

apiVersion: v1
appVersion: "1.0"
description: Kubernetes deprecated API versions exporter chart
name: kdave
version: 0.1.3
maintainers:
  - name: Ahmed ElBakry
    email: eng.ahmed.elbakry@gmail.com
