{{- if .Values.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kdave.fullname" . }}-psp
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}
    app: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kdave.fullname" . }}-psp
subjects:
- kind: ServiceAccount
  name: {{ template "kdave.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}