apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "kdave.fullname" . }}-pvc
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
